# path to the foundation/artifacts/makefile/modules
# https://github.com/williamwissemann/foundation


ARTIFACTS ?= ../../artifacts
MAKE_MODUALS = ${ARTIFACTS}/makefile/modules

HELP_FILTER = help|python|docker

include $(MAKE_MODUALS)/Makefile.*

PACKAGE={{cookiecutter.package_name}}
TAG=dev